- hosts: all
  become: yes
  tasks:
    - name: install software packages
      yum:
        name: "{{ item}}"
        state: present
      loop:
        - git
        - java-11-openjdk
        - jenkins
        - httpd
