- hosts: all
  become: True
  tasks:
    - name: installing multiple
      yum: name='{{item}}' state=installed
      with_items:
             - httpd
             - mysql
             - docker
             - java
             - tree
             - git  
